# Generated by Django 6.0 on 2025-12-22 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('author', 'Auteur'), ('contributor', 'Contributeur')], default='contributor', max_length=20, verbose_name='Rôle')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='api.project', verbose_name='Projet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Contributeur',
                'ordering': ['-created_time'],
                'unique_together': {('user', 'project')},
            },
        ),
    ]
